In [3]:
import numpy as np

def practice():
    size = np.random.randint(1,5)
    a = np.random.randint(-3,4,size).reshape(-1,1)
    b = np.random.randint(-3,4,size).reshape(-1,1)
    print("a = ")
    print(a)
    print()
    print("b = ")
    print(b)
    print()
    answer = int(input("What is np.dot(a.T,b), as a scalar?  "))
    print()
    expected = np.dot(a.T, b)[0][0]
    if answer == expected:
        print("Good job!")
        return True
    else:
        print("\nActually, it is ", expected)
        print("Calculation:", " + ".join(f"({x}*{y})" for x,y in zip(a.reshape(-1), b.reshape(-1))))
        time.sleep(2)
        return False

goal = 5
correct = 0
while correct < goal:
    print("="*40)
    print(f"Get {goal-correct} in a row correct to finish!")
    print("="*40)
    print()
    if practice():
        correct += 1
    else:
        correct = 0
    print()
        
print(f"Nice, you got {goal} in a row correct!")

Get 5 in a row correct to finish!

a = 
[[0]
 [0]]

b = 
[[3]
 [2]]

What is np.dot(a.T,b), as a scalar?  0

Good job!

Get 4 in a row correct to finish!

a = 
[[-3]
 [ 0]]

b = 
[[-2]
 [ 2]]

What is np.dot(a.T,b), as a scalar?  6

Good job!

Get 3 in a row correct to finish!

a = 
[[-1]
 [ 0]]

b = 
[[ 0]
 [-3]]

What is np.dot(a.T,b), as a scalar?  0

Good job!

Get 2 in a row correct to finish!

a = 
[[ 2]
 [-3]
 [ 1]]

b = 
[[2]
 [3]
 [2]]

What is np.dot(a.T,b), as a scalar?  -3

Good job!

Get 1 in a row correct to finish!

a = 
[[0]
 [2]]

b = 
[[2]
 [0]]

What is np.dot(a.T,b), as a scalar?  0

Good job!

Nice, you got 5 in a row correct!


# Part 2

In [4]:
def practice(cols):
    rows = np.random.randint(3, 7)
    A = np.random.randint(-3,4,(rows, cols))
    b = np.random.randint(-3,4,cols).reshape(-1,1)
    print("A = ")
    print(A)
    print()
    print("b = ")
    print(b)
    print()
    M = np.dot(A,b).astype(object)
    pos = np.random.randint(0,rows)
    expected, M[pos,0] = M[pos,0], "x"
    print("np.dot(A,b) = ")
    print(M)    
    print()
    answer = int(input("What is 'x'?  "))
    print()
    if answer == expected:
        print("Good job!")
        return True
    else:
        print("\nActually, it is ", expected)
        print("Calculation:", " + ".join(f"({x}*{y})" for x,y in zip(A[pos].reshape(-1), b.reshape(-1))))
        time.sleep(2)
        return False

goal = 3
correct = 0
while correct < goal:
    print("="*40)
    print(f"Get {goal-correct} in a row correct to finish!")
    print("="*40)
    print()
    if practice(correct+2):
        correct += 1
    else:
        correct = 0
    print()
        
print(f"Nice, you got {goal} in a row correct!")

Get 3 in a row correct to finish!

A = 
[[ 2  3]
 [ 2  0]
 [-3  2]
 [ 3 -1]]

b = 
[[-1]
 [-2]]

np.dot(A,b) = 
[[-8]
 [-2]
 ['x']
 [-1]]

What is 'x'?  -1

Good job!

Get 2 in a row correct to finish!

A = 
[[ 3  3  0]
 [-2  0 -1]
 [ 3 -2 -2]
 [ 3  2 -2]
 [-2  0 -3]]

b = 
[[0]
 [2]
 [0]]

np.dot(A,b) = 
[[6]
 [0]
 [-4]
 [4]
 ['x']]

What is 'x'?  0

Good job!

Get 1 in a row correct to finish!

A = 
[[ 2  0 -1 -3]
 [ 3 -2  1  0]
 [-1 -2  3  3]
 [-1 -3  3  1]]

b = 
[[ 0]
 [ 2]
 [-3]
 [ 1]]

np.dot(A,b) = 
[[0]
 [-7]
 [-10]
 ['x']]

What is 'x'?  -14

Good job!

Nice, you got 3 in a row correct!


# Part 3

In [9]:
import numpy as np

A = np.array([
    [10,0,1],
    [2,8,1],
    [4,4,1],
])
b = np.array([7,5,5]).reshape(-1,1)

x = np.linalg.solve(A, b)
apple_val, banana_val, basket_val = x.reshape(-1)

print("Apple Value:", apple_val)
print("Banana Value:", banana_val)
print("Basket Value:", basket_val)

Apple Value: 0.5
Banana Value: 0.24999999999999994
Basket Value: 2.0
